### PR TITLE
Generator

### PR DESCRIPTION
**Pull request by Gholgot**
Hello,

Following Sébastien Chopin's PR, we created a small utility function that hooks to Nuxt `generate` command, queries all your Prismic documents and runs the link resolver on them. It should create an array of Prismic related routes that will be fed to the generator.

It should also work if users already defined their own routes!

Happy to discuss it further :)

### CODE REVIEW

**Comment by hypervillain** [comment]
Small todo: remove duplicates!

**Comment by Gholgot** [comment]
_Jest IF/ELSE Statement_
After many attempts and after taking a look at Jest documentation, I decided to ignore the IF/ELSE statement inside fetchRoutes function starting at line 46 inside index.js file.

I was thinking about moving fetchRoutes out of the options.generate.routes function.
@jamespegg  feel free to share any advices or good practices that you think might help me 😀

Appart from that PR is ready to be accepted, a code review can be useful in case any bad choices were made.

**Comment by Atinux** [comment]
Hey @Gholgot 

Nice work, just so you know, I plan to import this module inside Nuxt: https://github.com/nuxt/nuxtjs.org/tree/master/modules/crawler

This way, we will follow every Nuxt link from the page (starting with the homepage) to generate all of them without having to use `generate.routes` :)

**Comment by jamespegg** [comment]
Interesting, I actually did something very similar when I was working on generating a sitemap. So initially I went down a similar pattern of using a recursive function, but also found this was difficult to test. In the end I simplified it a lot by just using a `do...while` loop. Something like this (I've just hacked it together and not run it, just illustrates how it could work);

```
if (!options.disableDefaultGenerator) {

  this.nuxt.hook('generate:before', async () => {
    const client = await Prismic.client(options.endpoint);
    const routes = []
    let next
    let page = 1

    do {
      let documents = await api.query('', { pageSize: 1, page})

      routes = routes.concat(documents.results.map(moduleOptions.linkResolver))

      next = documents.next_page
      page ++;
    } while (next)

    this.options.generate.routes = routes
  })
}
```

This becomes a little bit easier to unit test because you don't end up nesting multiple async functions. You should be able to mock the Prismic client and control the flow that way to get full test coverage

**Comment by arnaudlewis** [comment]
It still needs to be improved. In the current state it relies on the link resolver but if that link resolver build complex urls that requires some fetchLinks, then it won’t be working with just a loop over the documents.
We have something in the pipe to improve the way that we handle link resolving but it needs to be done before finishing the generate.

**Comment by Gholgot** [comment]
Changes made in this branch are no longer required because of the improvement that Atinux has made here : 
https://github.com/nuxt/nuxtjs.org/commit/9747520344af7bb08a410143cbe046bf27b418bc

**Pull request closed without merging**
